Bootstrap: localimage
From: ../base/conda-base.sif

%help
Singularity container for cheminformatics and deep learning

%files
    env.yml /opt/environment.yml
    post-install.sh /opt/post-install.sh

%environment
    PATH=${PATH}:/opt/conda/envs/myenv/bin
    LD_LIBRARY_PATH=/opt/conda/envs/myenv/lib:${LD_LIBRARY_PATH}

%post
    #conda update -y conda
    conda install -y "conda<4.13"
    mamba env create -f /opt/environment.yml
    conda clean -afy
    rm -rf /root/.cache/pip/*
    . /opt/conda/etc/profile.d/conda.sh
    conda activate myenv
    jupyter lab build
    . /opt/post-install.sh

%runscript 
    exec "$@"

%apprun print_version
    python --version

%apphelp python_version
    Print python version and exit

%apprun python_shell
    python

%apphelp python_shell
    Launch python shell

%apprun python_script
    python "$@"

%apphelp python_script
    Run a python script
