Bootstrap: localimage
From: ../base/conda-base.sif
#From: msu_dl_0.sif

%help
Singularity container for cheminformatics and deep learning

%files
    env.yml /opt/environment.yml

%environment
    PATH=${PATH}:/opt/conda/envs/myenv/bin
    LD_LIBRARY_PATH=/opt/conda/envs/myenv/lib:${LD_LIBRARY_PATH}
    LANG=en_US.UTF-8
    LC_CTYPE="C.UTF-8 R"
    LC_NUMERIC="C.UTF-8 R"
    LC_TIME="C.UTF-8 R"
    LC_COLLATE="C.UTF-8 R"
    LC_MONETARY="C.UTF-8 R"
    LC_MESSAGES="C.UTF-8 R"
    LC_PAPER="C.UTF-8 R"
    LC_NAME="C.UTF-8 R"
    LC_ADDRESS="C.UTF-8 R"
    LC_TELEPHONE="C.UTF-8 R"
    LC_MEASUREMENT="C.UTF-8 R"
    LC_IDENTIFICATION="C.UTF-8 R"

%post
    gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    gpg -a --export E298A3A825C0D65DFD57CBB651716619E084DAB9 | apt-key add -
    add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
    apt update
    export DEBIAN_FRONTEND=noninteractive
    export DEBCONF_NONINTERACTIVE_SEEN=true
    echo -e "tzdata tzdata/Areas select US\ntzdata tzdata/Zones/US select New_York" >> tzdata_preseed.txt
    debconf-set-selections tzdata_preseed.txt
    apt install -y tzdata
    apt install -y r-base
    apt install -y libgmp3-dev libmpfr-dev
    R -e "install.packages(c('FNN', 'igraph', 'scales', 'Rcpp', 'RcppEigen', 'BH'), repos='https://cran.microsoft.com/snapshot/2019-08-01/')"
    R -e "install.packages(c('TDA'), repos='https://cran.microsoft.com/snapshot/2019-08-01/')"

    conda update -y conda
    mamba env create -f /opt/environment.yml
    conda clean -afy
    . /opt/conda/etc/profile.d/conda.sh
    conda activate myenv

%runscript 
    exec "$@"

%apprun print_version
    python --version

%apphelp python_version
    Print python version and exit

%apprun python_shell
    python

%apphelp python_shell
    Launch python shell

%apprun python_script
    python "$@"

%apphelp python_script
    Run a python script
