Bootstrap: docker
From: nvidia/cuda:10.1-runtime

%help
Singularity container for training and generating predictions using Chemprop (https://github.com/swansonk14/chemprop)


%files
    chemprop.yml /opt/environment.yml

%environment
    PATH=${PATH}:/opt/conda/envs/chemprop/bin
    OE_LICENSE=/nfs/grid/software/hpcc/apps/Linux-x86_64-RHEL6/openeye/oe_license.txt

%post
    apt-get update -y
    apt-get install -y software-properties-common
    apt-add-repository -y ppa:graphics-drivers/ppa
    apt-get install -y wget git
    rm -rf /var/lib/apt/lists/*
    
    rm -rf /var/lib/apt/lists/*
    wget "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O setup.sh 
    bash setup.sh -p /opt/conda -b 
    rm -rf setup.sh
    update-alternatives --install /usr/local/bin/conda conda /opt/conda/bin/conda 1
    
    conda update -y conda
    conda env create -f /opt/environment.yml
    conda clean -afy
    . /opt/conda/etc/profile.d/conda.sh
    conda activate chemprop
    pip install git+https://github.com/bp-kelley/descriptastorus

%runscript 
    exec "$@"

%apprun print_version
    python --version

%apprun python_shell
    python

%apprun python_script
    python "$@"

