Bootstrap: docker
From: nvidia/cuda:9.2-runtime

%help
Singularity base container for python apps with conda

%post
    apt-get update -y
    apt-get install -y zsh
    apt-get install -y software-properties-common
    apt-add-repository -y ppa:graphics-drivers/ppa
    apt-get install -y wget git build-essential
    apt-get install -y libcairo2 libcairo2-dev
    apt-get install -y libaio1
    
    rm -rf /var/lib/apt/lists/*
    wget "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O setup.sh 
    bash setup.sh -p /opt/conda -b 
    rm -rf setup.sh
    update-alternatives --install /usr/local/bin/conda conda /opt/conda/bin/conda 1
    
    conda update -y conda
    conda install mamba -n base -c conda-forge -y
    update-alternatives --install /usr/local/bin/mamba mamba /opt/conda/bin/mamba 1
    conda clean -afy

%runscript 
    exec "$@"

%apprun print_version
    python --version

%apphelp python_version
    Print python version and exit

%apprun python_shell
    python

%apphelp python_shell
    Launch python shell

%apprun python_script
    python "$@"

%apphelp python_script
    Run a python script
