load("medsci")
load("matlab/R2017a")
load("medsci")
load("hpc/eb-2017-core")
load("ifort/.2017.1.132-GCC-5.4.0-2.27")
load("impi/2017.1.132")
load("OpenBabel")
load("cuda-cudnn/10.0.130")
load("miniconda3")
set_alias("pythonsh", "/hpc/grid/wip_adw_compsci/workspace/projects/deep_learning/Python/msu_dl_py3/bin/pythonsh")
execute {cmd="source activate /hpc/grid/wip_adw_compsci/workspace/projects/deep_learning/Python/msu_dl_py3", modeA={"load"}}
append_path ("PATH","/hpc/grid/adw_hpcc_workspace/users/sreshv/Projects/MSU_Potency_Model/wip/software/downloads/jackal_64bit/bin")
setenv ("AUTODOCK_TOOLS", "/hpc/grid/wip_adw_compsci/workspace/projects/deep_learning/Python/msu_dl_py3/MGLToolsPckgs/AutoDockTools/Utilities24")
setenv ("JACKALDIR", "/hpc/grid/adw_hpcc_workspace/users/sreshv/Projects/MSU_Potency_Model/wip/software/downloads/jackal_64bit/bin/jackal.dir")
append_path ("PYTHONPATH","/hpc/grid/wip_adw_compsci/workspace/projects/deep_learning/Python/msu_dl_py3/MGLToolsPckgs")
execute {cmd="conda deactivate", modeA={"unload"}}
